wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.6
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1691456685.106158
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 23
      4: 3.9.6
      5: 0.15.5
      8:
      - 1
      - 3
      - 5
hidden_size:
  desc: null
  value: 256
learning_rate:
  desc: null
  value: 0.01
batch_size:
  desc: null
  value: 50
max_iterations:
  desc: null
  value: 3000
